Do not fail on burgr-notify-promotion

diff --git a/bin/burgr-notify-promotion b/bin/burgr-notify-promotion
--- a/bin/burgr-notify-promotion
+++ b/bin/burgr-notify-promotion
@@ -76,4 +76,8 @@ cat > $BURGR_FILE <<EOF
 }
 EOF
 echo "url ${BURGR_URL}/api/promote/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_BUILD_ID}"
-curl -sfSL -X POST -d @$BURGR_FILE -H "Content-Type:application/json" -u"${BURGR_USERNAME}:${BURGR_PASSWORD}" "${BURGR_URL}/api/promote/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_BUILD_ID}"
+{
+  curl -sfSL -X POST -d @$BURGR_FILE -H "Content-Type:application/json" -u"${BURGR_USERNAME}:${BURGR_PASSWORD}" "${BURGR_URL}/api/promote/${CIRRUS_REPO_OWNER}/${CIRRUS_REPO_NAME}/${CIRRUS_BUILD_ID}"   
+} || { 
+    echo "burgr promotion notification failed"
+}
